baseURL = "https://tamada.github.io/spellout"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Spellout"
googleAnalytics = ""
theme = ["github.com/tamada/hugo_theme_mod", "github.com/nunocoracao/blowfish/v2"]

[params]
logo = "icons/logo.svg"
description = ""
dateFormat = "2006-01-02"
copyright = "Copyright &copy; 2026 by Haruaki Tamada. Made with [Hugo](https://gohugo.io/). Deployed to [GitHub Pages](https://pages.github.com/)."

[menus]
[[menus.main]]
    name = "üèÉ Usage"
    pageRef = "/usage"
    weight = 30
[[menus.main]]
    name = "‚öìÔ∏è Install"
    pageRef = "/install"
    weight = 50
[[menus.main]]
    identifier = "haruaki-tamada"
    pre = "haruaki-tamada"
    url = "https://tamada.github.io"
    weight = 100
[[menus.main]]
    identifier = "github"
    pre = "github"
    url = "https://github.com/tamada/spellout"
    weight = 200
[[menus.footer]]
    name = ":smile: About"
    pageRef = "/about"
    weight = 50

[module]
[[module.imports]]
path = "github.com/tamada/hugo_theme_mod"
